### ISSUE TITLE
Trying to create SystemGenerator from RDKit converted openff topology

### ISSUE THREAD

**Issue by tarungog** [openmm/pdbfixer#200]
Hello,

![image](https://user-images.githubusercontent.com/15879686/78626581-2ff37f00-785d-11ea-8221-59f9e197f080.png)

Can someone explain this error to me? It happens at the create_system line.
```AttributeError: 'Topology' object has no attribute 'getPeriodicBoxVectors'```

**Comment by peastman** [comment]
It looks like this is a question about openforcefield, not PDBFixer.  I don't see any PDBFixer classes in there.

**Comment by jchodera** [comment]
@tarungog : In future, could you open issues in https://github.com/openmm/openmmforcefields?

It looks like the issue is that you're feeding an `openforcefield.topology.Topology` object to `ofmol.to_topology()`, but it instead expects a `simtk.openmm.app.Topology`. 

Try changing `ofmol.to_topology()` to `ofmol.to_topology().to_openmm()`.

**Comment by tarungog** [comment]
ahh sorry! got the wrong repo. closing it out, thanks for the pointer @jchodera.
