### ISSUE TITLE
findMissingResidues does not detect residues missing from structure

### ISSUE THREAD

**Issue by YoavShamir5** [openmm/pdbfixer#300]
I tried running the following on a PDB structure (PDB ID: 5J7S) the clearly has missing residues (e.g. ALA46 and PHE47), but those are not detected:

findMissingResidues
fixer = PDBFixer(filename='5j7s.pdb')
print(fixer)
fixer.findMissingResidues()
print("missing: ", fixer.missingResidues)

**missing:  {}**

Is there a syntax issue here?

**Comment by peastman** [comment]
To identify missing residues, it tries to match the sequence in the SEQRES records to the one in the ATOM records.  In the case of that entry, they don't match.  If you look at the ATOM records, you'll see there's a huge gap right in the middle of chain A.  The residue numbers jump from 303 to 468.  There's nothing corresponding in the SEQRES records.  Since it can't figure out how to align them, it doesn't know what to add.

**Comment by YoavShamir5** [comment]
Got it, thanks for this informative reply.

**Comment by peastman** [comment]
When you run into cases like this, the workaround is to set `missingResidues` yourself.  You can tell it what you want it to add.

**Comment by YoavShamir5** [comment]
Following your advice, I tried the following in order to add missing residues ALA46 and PHE47:

fixer = PDBFixer(filename='5j7s.pdb')
fixer.missingResidues = {(0, 20): ['ALA', 'PHE']}
fixer.findMissingAtoms()
print("missing: ", fixer.missingAtoms)

**missing: {}**


Why are not atoms annotated as missing? Am I making a syntax mistake here? Thanks for your help.

**Comment by peastman** [comment]
`findMissingAtoms()` only records atoms that are missing from existing residues.  Missing residues are tracked separately in `missingResidues`.  They both get added when you call `addMissingAtoms()`.

https://github.com/openmm/pdbfixer/blob/f9aae0bcfd7b95661cb524c5e52ac71f6b71bf7b/pdbfixer/pdbfixer.py#L1055-L1056

**Comment by YoavShamir5** [comment]
Thank you for the info. I tried the following: 

**fixer = PDBFixer(filename='5j7s.pdb')
fixer.missingResidues = {(0, 19): ['ALA', 'PHE']}
fixer.findMissingAtoms()
fixer.addMissingAtoms()
PDBFile.writeFile(fixer.topology, fixer.positions, open('out_57js.pdb', 'w'))**


The output file includes the added ALA and PHE, but they clash and have a pose that does not seem to make sense. 
Is this the result of the residue completion algorithm, or is my syntax flawed?

![add_residues](https://github.com/user-attachments/assets/328e2017-f34d-44de-8e6e-af7560b3711c)

**Comment by YoavShamir5** [comment]
Also - the output file has the residues renumbered starting from 1. Is there a functionality to avoid this, keeping the original numbering? Thanks again

**Comment by peastman** [comment]
When adding missing residues it does its best to add them in places that don't clash with anything, but sometimes it can be challenging.  Try running it a few times and see if it does better.

When you call [`writeFile()`](http://docs.openmm.org/latest/api-python/generated/openmm.app.pdbfile.PDBFile.html#openmm.app.pdbfile.PDBFile.writeFile) you can add the argument `keepIds=True` to tell it to preserve all existing IDs rather than generating new ones.

**Comment by peastman** [comment]
I think some of the problem is coming from the waters.  The need to avoid them is constraining where it can put the new residues.  If I add the line

```python
fixer.removeHeterogens(keepWater=False)
```

I get a somewhere better result, though it's still not perfect.  This might be a case where hand editing is needed.  It's a cramped space to fit three residues into.
